Repository JodaOrg/joda-time, pull requests merged in 2022-10, with the labels that each got.

#642 Add slovak translation to messages_sk.properties
  src/main/java/org/joda/time/format/messages_sk.properties
Labels: RFE, Fixed

#644 Create messages_fi.properties
  src/main/java/org/joda/time/format/messages_fi.properties
Labels: RFE, Fixed

#645 Add catalan translations
  src/main/java/org/joda/time/format/messages_ca.properties
Labels: RFE, Fixed

#647 add basque (eu) translations
  src/main/java/org/joda/time/format/messages_eu.properties
Labels: RFE, Fixed

#657 Fix Javadoc issues
  src/main/java/org/joda/time/DateMidnight.java
  src/main/java/org/joda/time/DateTime.java
  src/main/java/org/joda/time/DateTimeZone.java
  src/main/java/org/joda/time/Duration.java
  src/main/java/org/joda/time/IllegalFieldValueException.java
  src/main/java/org/joda/time/Instant.java
  src/main/java/org/joda/time/Interval.java
  src/main/java/org/joda/time/LocalDate.java
  src/main/java/org/joda/time/LocalDateTime.java
  src/main/java/org/joda/time/LocalTime.java
  src/main/java/org/joda/time/MonthDay.java
  src/main/java/org/joda/time/MutableDateTime.java
  src/main/java/org/joda/time/MutableInterval.java
  src/main/java/org/joda/time/MutablePeriod.java
  src/main/java/org/joda/time/Partial.java
  src/main/java/org/joda/time/Period.java
  src/main/java/org/joda/time/ReadableDateTime.java
  src/main/java/org/joda/time/ReadableInstant.java
  src/main/java/org/joda/time/TimeOfDay.java
  src/main/java/org/joda/time/YearMonth.java
  src/main/java/org/joda/time/base/BasePartial.java
  src/main/java/org/joda/time/base/BaseSingleFieldPeriod.java
  src/main/java/org/joda/time/chrono/AssembledChronology.java
  src/main/java/org/joda/time/chrono/BasicSingleEraDateTimeField.java
  src/main/java/org/joda/time/chrono/BuddhistChronology.java
  src/main/java/org/joda/time/chrono/GJChronology.java
  src/main/java/org/joda/time/chrono/LenientChronology.java
  src/main/java/org/joda/time/chrono/LimitChronology.java
  src/main/java/org/joda/time/chrono/StrictChronology.java
  src/main/java/org/joda/time/chrono/ZonedChronology.java
  src/main/java/org/joda/time/convert/ConverterManager.java
  src/main/java/org/joda/time/convert/StringConverter.java
  src/main/java/org/joda/time/field/AbstractReadableInstantFieldProperty.java
  src/main/java/org/joda/time/field/BaseDateTimeField.java
  src/main/java/org/joda/time/field/FieldUtils.java
  src/main/java/org/joda/time/field/LenientDateTimeField.java
  src/main/java/org/joda/time/field/PreciseDurationDateTimeField.java
  src/main/java/org/joda/time/field/StrictDateTimeField.java
  src/main/java/org/joda/time/field/UnsupportedDateTimeField.java
  src/main/java/org/joda/time/field/UnsupportedDurationField.java
  src/main/java/org/joda/time/format/DateTimeFormatter.java
  src/main/java/org/joda/time/format/DateTimeFormatterBuilder.java
  src/main/java/org/joda/time/format/DateTimeParserBucket.java
  src/main/java/org/joda/time/format/DateTimePrinter.java
  src/main/java/org/joda/time/format/FormatUtils.java
  src/main/java/org/joda/time/format/ISODateTimeFormat.java
  src/main/java/org/joda/time/format/InternalPrinter.java
  src/main/java/org/joda/time/format/PeriodFormat.java
  src/main/java/org/joda/time/format/PeriodFormatter.java
  src/main/java/org/joda/time/format/PeriodFormatterBuilder.java
  src/main/java/org/joda/time/format/PeriodPrinter.java
  src/main/java/org/joda/time/tz/ZoneInfoCompiler.java
Labels: Bug, Fixed

#656 Add Chinese translation of word-based periods (#643)
  src/main/java/org/joda/time/format/messages_zh.properties
Labels: RFE, Fixed

#668 Updates after localization PRs
  pom.xml
  src/changes/changes.xml
  src/test/java/org/joda/time/format/TestPeriodFormat.java
Labels: Fixed, Task
